/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "response": {
        "SERVER_ERROR": string;
        "MODEL_NOT_FOUND": string;
    };
    "validation": {
        "isNotEmpty": string;
        "isEmail": string;
        "isString": string;
        "isBoolean": string;
        "isMin": string;
        "isMinLength": string;
        "isMax": string;
        "isMaxLength": string;
        "isEnum": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
